name: Audit on push

# Run the following job on every push request modifying one of those two files.
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'

jobs:
  # Check for known security vulnerabilities.
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
